[package]
name = "aria_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aria_models = { path = "../models" }
aria_shared = { path = "../shared" }
aria_store = { path = "../store" }
anyhow = "1.0.66"
blake3 = "1.3.1"
bytes = "1.2.1"
chrono = "0.4.22"
dirs = "4.0.0"
futures-channel = "0.3.25"
futures-core = "0.3.25"
futures-util = "0.3.25"
image = "0.24.4"
once_cell = "1.16.0"
rand = "0.8.5"
regex = "1.7.0"
serde = "1.0.147"
serde_derive = "1.0.147"
serde_json = "1.0.87"
tokio = "1.21.2"
tracing = "0.1.37"
uuid = { version = "1.2.1", features = ["v4"] }
