[package]
name = "aria_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aria_models = { path = "../models" }
aria_shared = { path = "../shared" }
aria_store = { path = "../store" }
anyhow = "1.0.64"
blake3 = "1.3.1"
chrono = "0.4.22"
dirs = "4.0.0"
futures-channel = "0.3.24"
image = "0.24.3"
mime2ext = "0.1.52"
rand = "0.8.5"
regex = "1.6.0"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"
tokio = "1.21.0"
tracing = "0.1.36"
