[package]
name = "aria_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aria_models = { path = "../models" }
aria_shared = { path = "../shared" }
aria_store = { path = "../store" }
anyhow = "1.0.71"
blake3 = "1.3.3"
bytes = "1.4.0"
chrono = "0.4.24"
dirs = "5.0.1"
futures-channel = "0.3.28"
futures-core = "0.3.28"
futures-util = "0.3.28"
image = { version = "0.24.6", features = ["webp-encoder"] }
once_cell = "1.17.1"
rand = "0.8.5"
regex = "1.8.1"
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
tokio = "1.28.1"
toml = "0.7.4"
tracing = "0.1.37"
uuid = { version = "1.3.3", features = ["v4"] }
