[package]
name = "aria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aria_core = { path = "../core" }
aria_models = { path = "../models" }
aria_shared = { path = "../shared" }
anyhow = "1.0.75"
axum = { version = "0.6.20" , features = ["headers", "macros", "multipart"] }
chrono = "0.4.26"
clap = { version = "4.3.22", features = ["derive"] }
futures = "0.3.28"
futures-channel = "0.3.28"
jsonwebtoken = "8.3.0"
regex = "1.9.3"
serde = "1.0.183"
serde_derive = "1.0.183"
serde_json = "1.0.105"
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-tungstenite = "0.20.0"
tower-http = { version = "0.4.3", features = ["fs", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.4.1", features = ["serde"] }
