[package]
name = "aria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aria_core = { path = "../core" }
aria_models = { path = "../models" }
aria_shared = { path = "../shared" }
anyhow = "1.0.66"
axum = { version = "=0.6.0-rc.4" , features = ["headers", "macros", "multipart"] }
axum-extra = { version = "=0.4.0-rc.2", features = ["spa"] }
chrono = "0.4.22"
clap = { version = "4.0.22", features = ["derive"] }
futures = "0.3.25"
futures-channel = "0.3.25"
jsonwebtoken = "8.1.1"
regex = "1.7.0"
serde = "1.0.147"
serde_derive = "1.0.147"
serde_json = "1.0.87"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["macros", "signal"] }
tokio-tungstenite = "0.17.2"
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
uuid = { version = "1.2.1", features = ["serde"] }
