[package]
name = "aria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aria_core = { path = "../core" }
aria_models = { path = "../models" }
aria_shared = { path = "../shared" }
anyhow = "1.0.75"
axum = { version = "0.6.20" , features = ["headers", "macros", "multipart"] }
axum-client-ip = "0.4.2"
chrono = "0.4.31"
clap = { version = "4.4.7", features = ["derive"] }
futures = "0.3.29"
futures-channel = "0.3.29"
jsonwebtoken = "9.1.0"
regex = "1.10.2"
serde = "1.0.190"
serde_derive = "1.0.190"
serde_json = "1.0.107"
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-tungstenite = "0.20.1"
tower-http = { version = "0.4.4", features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.5.0", features = ["serde"] }
