[package]
name = "aria_store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
chrono = "0.4.24"
serde = "1.0.163"
serde_derive = "1.0.163"
sqlx = { version = "0.6.3", features = ["chrono", "ipnetwork", "offline", "postgres", "runtime-tokio-rustls", "uuid"] }
tokio = "1.28.1"
tracing = "0.1.37"
uuid = "1.3.3"
